// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChzM13JASlSpAQf3P5eQId78W1AwsUIlo',
    appId: '1:1057037815712:web:1e0b23409b9567bf255ec5',
    messagingSenderId: '1057037815712',
    projectId: 'medigay-65f83',
    authDomain: 'medigay-65f83.firebaseapp.com',
    storageBucket: 'medigay-65f83.appspot.com',
    measurementId: 'G-45J7G47THS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChzM13JASlSpAQf3P5eQId78W1AwsUIlo',
    appId: '1:1057037815712:android:1e0b23409b9567bf255ec5',
    messagingSenderId: '1057037815712',
    projectId: 'medigay-65f83',
    storageBucket: 'medigay-65f83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzM13JASlSpAQf3P5eQId78W1AwsUIlo',
    appId: '1:1057037815712:ios:1e0b23409b9567bf255ec5',
    messagingSenderId: '1057037815712',
    projectId: 'medigay-65f83',
    storageBucket: 'medigay-65f83.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzM13JASlSpAQf3P5eQId78W1AwsUIlo',
    appId: '1:1057037815712:macos:1e0b23409b9567bf255ec5',
    messagingSenderId: '1057037815712',
    projectId: 'medigay-65f83',
    storageBucket: 'medigay-65f83.appspot.com',
  );
} 